spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/art_sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://jaehodb.cwa8drqjuwbz.ap-northeast-2.rds.amazonaws.com:3306/art_sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#    username: hongyj
    username: artSharing
#    password: sec031031!
    password: 1q2w3e


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB

resources:
  image-locations : /home/ubuntu/ec2-user/img/
  image-url : 52.78.45.58:8080

